<a href="https://colab.research.google.com/github/msoly25/DS-2002-F25/blob/main/DS_3001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
! git clone https://github.com/msoly25/scratchpad
%run ./scratchpad/get_data.py

Cloning into 'scratchpad'...
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (2/2), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 24 (delta 0), reused 0 (delta 0), pack-reused 22 (from 1)
Receiving objects: 100% (24/24), 25.56 KiB | 6.39 MiB/s, done.
Resolving deltas: 100% (5/5), done.
Downloading course data...
Download complete
Extracting data files...
Data extracted

In [4]:
import pandas as pd
df = pd.read_csv('/content/data/mn_police_use_of_force.csv', encoding = 'utf_8')
df.head(2)

,response_datetime,problem,is_911_call,primary_offense,subject_injury,force_type,force_type_action,race,sex,age,type_resistance,precinct,neighborhood
0,2016/01/01 00:47:36,Assault in Progress,Yes,DASLT1,NaN,Bodily Force,Body Weight to Pin,Black,Male,20.0,Tensed,1,Downtown East
1,2016/01/01 02:19:34,Fight,No,DISCON,NaN,Chemical Irritant,Personal Mace,Black,Female,27.0,Verbal Non-Compliance,1,Downtown West

In [5]:
df.shape

(12925, 13)

In [6]:
import pandas as pd

In [8]:
df['force_type'].describe()

count            12925
unique              11
top       Bodily Force
freq              9430
Name: force_type, dtype: object